---
title: "Lab 3A: Starting with data"
author: "Grace Lawson"
date: "9.7.20"
output: html_document
---

```{r, eval = FALSE}
library("tidyverse")
```


```{r, eval = FALSE}
download.file(url = "https://ndownloader.figshare.com/files/2292169",
              destfile = "data/portal_data_joined.csv")
```

# Load data
```{r}
surveys <- read.csv("data/portal_data_joined.csv")

# View data
head(surveys)
str(surveys)
```


# Inspecting data.frame Objects
```{r}
# Size
dim(surveys)
nrow(surveys)
ncol(surveys)
```

```{r}
# Content
head(surveys)
tail(surveys)
```

```{r, results = "hide"}
# Names
names(surveys)
rownames(surveys)
```

```{r}
# Summary
str(surveys)
summary(surveys)
```

## Challenge
```{r}
# class = data frame
# rows = 34786, columns = 13
# species = 48
```

# Indexing and subsetting data frames
```{r, results = "hide"}
# first element in the first column of the data frame (as a vector)
surveys[1, 1]   
# first element in the 6th column (as a vector)
surveys[1, 6]   
# first column of the data frame (as a vector)
surveys[, 1]    
# first column of the data frame (as a data.frame)
surveys[1]      
# first three elements in the 7th column (as a vector)
surveys[1:3, 7] 
# the 3rd row of the data frame (as a data.frame)
surveys[3, ]    
# equivalent to head_surveys <- head(surveys)
head_surveys <- surveys[1:6, ] 
```

```{r, results = "hide"}
surveys[, -1] # The whole data frame, except the first column
surveys[-(7:34786), ] # Equivalent to head(surveys)
```

```{r, results = "hide"}
surveys["species_id"]       # Result is a data.frame
surveys[, "species_id"]     # Result is a vector
surveys[["species_id"]]     # Result is a vector
surveys$species_id          # Result is a vector
```

## Challenge
```{r}
# 1
surveys_200 <- surveys[200,]
```

```{r}
# 2
surveys[34786,]
tail(surveys)
surveys[nrow(surveys),]
surveys_last <- surveys[34786,]
```

```{r}
# 3 
surveys_middle <- surveys[nrow(surveys) / 2 ,]
```

```{r}
# 4
surveys_head <- surveys[-(7:nrow(surveys)), ]
```


# Factors
```{r}
# Examples
sex <- factor(c("male", "female", "female", "male"))
levels(sex)
nlevels(sex)
```

```{r}
# Levels in sex vector
sex # current order
```
