---
title: "Lab 3B: Manipulating data"
author: "Grace Lawson"
date: "9.7.20"
output: html_document
---

```{r}
library("tidyverse")
```

```{r}
surveys <- read_csv("data/portal_data_joined.csv")
```

```{r}
## inspect the data
str(surveys)
```

# Selecting columns and filtering rows
```{r}
select(surveys, plot_id, species_id, weight)

select(surveys, -record_id, -species_id)

filter(surveys, year == 1995)

```

# Pipes
```{r}
# Intermediate steps
surveys2 <- filter(surveys, weight < 5)
surveys_sml <- select(surveys2, species_id, sex, weight)
```

```{r}
# Nested functions
surveys_sml <- select(filter(surveys, weight < 5), species_id, sex, weight)
```

```{r}
# Pipes
surveys_sml <- surveys %>% 
  filter(weight < 5) %>% 
  select(species_id, sex, weight)
surveys_sml
```

### Challenge
```{r}
surveys %>% 
  filter(year < 1995) %>% 
  select(year, sex, weight) 
```

# Mutate
```{r}
surveys %>%
  mutate(weight_kg = weight / 1000)
```

```{r}
surveys %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)
```

```{r}
surveys %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```

### Challenge
```{r}
survey_hindfoot_data <- surveys %>% 
  filter(!is.na(hindfoot_length)) %>% 
  mutate(hindfoot_cm = hindfoot_length / 10) %>% 
  filter(hindfoot_cm < 3) %>% 
  select(species_id, hindfoot_cm)
survey_hindfoot_data
```

# Split-apply-combine data analysis and the summarize() function
```{r}
# Compute mean weight by sex
surveys %>%
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))
```

```{r}
# Group by multiple columns
surveys %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE)) %>% 
  tail()
# Remove NA values
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight))
```

# Reshaping with gather and spread
```{r}
# Spreading
surveys_gw <- surveys %>%
  filter(!is.na(weight)) %>%
  group_by(plot_id, genus) %>%
  summarize(mean_weight = mean(weight))

str(surveys_gw)
```

```{r}
surveys_spread <- surveys_gw %>%
  spread(key = genus, value = mean_weight)

str(surveys_spread)
```

```{r}
surveys_gw %>%
  spread(genus, mean_weight, fill = 0) %>%
  head()
```

```{r}
# Gathering
surveys_gather <- surveys_spread %>%
  gather(key = "genus", value = "mean_weight", -plot_id)

head(surveys_gather)
```

```{r}
surveys_spread %>%
  gather(key = "genus", value = "mean_weight", Baiomys:Spermophilus) %>%
  head()
```

### Challenge
```{r}
# 1
surveys_spread_genera <- surveys %>% 
  group_by(plot_id, year) %>% 
  summarize(n_genera = n_distinct(genus)) %>% 
  spread(year, n_genera)
head(surveys_spread_genera)
```

```{r}
# 2 
surveys_spread_genera %>% 
  gather(year, n_genera, -plot_id)
```

```{r}
# 3
surveys_long <- surveys %>% 
  gather("measurement", "value", hindfoot_length, weight)
head(surveys_long)
```

```{r}
# 4
surveys_long %>% 
  group_by(year, measurement, plot_type) %>% 
  summarize(mean_value = mean(value, na.rm = TRUE)) %>% 
  spread(measurement, mean_value)
```

# Exporting data
```{r}
# remove missing observations
surveys_complete <- surveys %>% 
  filter(!is.na(weight),
         !is.na(hindfoot_length),
         !is.na(sex))
```

```{r}
## Extract the most common species_id
species_counts <- surveys_complete %>%
    count(species_id) %>% 
    filter(n >= 50)

## Only keep the most common species
surveys_complete <- surveys_complete %>%
  filter(species_id %in% species_counts$species_id)
```

```{r}
dim(surveys_complete)
```

```{r}
write_csv(surveys_complete, path = "data/surveys_complete.csv")
```

